config/routes.rb
Rails.application.routes.draw do

  
  root 'pages#home'
  
  get '/about', to: 'pages#about'
  
  get '/signup', to: 'users#new'
  
  resources :users, except: [:new]
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy'
  resources :articles
  
  get '/mailer', to: 'mailer#new'
  post '/mailer', to: 'mailer#sendmail'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
  
end

app/models/mailer.rb
class Mailer
  
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :email, presence: true,
            length: { maximum: 120 },
            format: { with: VALID_EMAIL_REGEX }
            
  validates :subject, presence: true, length: { maximum: 50 }
  
  validates :message, presence: true, length: { maximum: 500 }
  
  def persisted?
    false
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true, 
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 20 }
            
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
            
  validates :email, presence: true,
            uniqueness: { case_sensitive: false },
            length: { maximum: 120 },
            format: { with: VALID_EMAIL_REGEX }
            
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must me logged in to perform that action"
      redirect_to root_path
    end
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :destroy, :show]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy
  ]
  
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    
    if @article.save
      flash[:success] = "Article is successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
      
  end
  
  def show
    
  end
  
  def edit
   
  end
  
  def destroy
    @article.destroy
    
    flash[:danger] = "Article successfully deleted"
    redirect_to articles_path
  end
  
  def update
    
    if @article.update(article_params)
      flash[:success] = "Article successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  private
    def set_article
      @article = Article.find(params[:id])
    end
    def article_params
      params.require(:article).permit(:title, :description)
    end
    
    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete your own articles"
        redirect_to root_path
      end
    end
  
end

app/controllers/mailer_controller.rb
class MailerController < ApplicationController
  require 'mailgun'
  
  def new
    
  end
  
  def sendmail
    email = params[:mailer][:email]
    subject = params[:mailer][:subject]
    message = params[:mailer][:message]
    
    # First, instantiate the Mailgun Client with your API key
    mg_client = Mailgun::Client.new 'key-9793adf968a4fb57cc6f619b58b98d4c'
    
    # Define your message parameters
    message_params =  { from: 'Fidiyo App <app@fidiyo.com>',
                        to: email,
                        subject: subject,
                        text: message
                      }
    
    # Send your message through the client
    result = mg_client.send_message('idevia.in', message_params).to_h!
    
    puts result
    
    if result
      flash[:success] = "Email has been sent"
    end
    
    render 'new'

  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    redirect_to articles_path if logged_in?
  end
  
  def about
    
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Invalid credentials"
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:danger] = "You have logged out successfully"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]
  
  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Alpha Blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end
  
  def edit
    
  end
  
  def update
    
    if @user.update(user_params)
      flash[:success] = "Your account was successfully updated"
      redirect_to articles_path
    else
      render 'edit'
    end
  end
  
  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end
  
  def destroy
    @user.destroy
    flash[:danger] = "User and all articles created by the user have been deleted"
    redirect_to users_path
  end
  
  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
    
    def set_user
      @user = User.find(params[:id])
    end
    
    
    
    def require_same_user
      if current_user != @user and !current_user.admin?
        flash[:danger] = "You can only edit your profile"
        redirect_to root_path
      end
    end
    
    def require_admin
      if logged_in? and !current_user.admin?
        flash[:danger] = "Only admin can perform that action"
        redirect_to root_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded-circle mt-3")
  end
end

app/views/articles/_articles.html.erb
  <% obj.each do |article| %>
    <article class="my-4 card">
      <div class="card-body">
        <h5>
          <%= link_to article.title, article_path(article) %>
        </h5>
        <small class="text-info">by <%= article.user.username if article.user %>,
        <%= time_ago_in_words(article.created_at) %> ago,
        last updated: <%= time_ago_in_words(article.updated_at) %> ago
        </small>
        <p class="lead"><%= truncate(article.description, length: 100) %></p>
        <% if logged_in? && ( current_user == article.user || current_user.admin? ) %>
          <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-secondary" %>
          <%= link_to 'Read', article_path(article), class: "btn btn-outline-info" %>
          <%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
        <% end %>
      </div>
    </article>
  <% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<%= form_for @article do |f| %>
  <div class="form-group row mt-4">
    
    <div class="col-sm-2">
      <%= f.label :title, class: "col-form-label" %>
    </div>
    
    <div class="col-sm-8">
      <%= f.text_field :title, class: "form-control", placeholder: "Title of the article" %>
    </div>
  </div>
  
  <div class="form-group row">
    
    <div class="col-sm-2">
      <%= f.label :description, class: "col-form-label" %>
    </div>
    
    <div class="col-sm-8">
      <%= f.text_area :description, class: "form-control", rows: "10", placeholder: "Description of the article" %>
    </div>
  </div>
  
  <div class="form-group row">
    <div class="col-sm-8 offset-sm-2">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
  
  

<% end %>

<p>
  <%= link_to '← Back to article listing', articles_path %>  
</p>

app/views/articles/edit.html.erb
<h1 class="text-center">Edit an article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing all articles</h1>


<%= render 'articles', obj: @articles %>

<%= will_paginate @clients, list_classes: %w(pagination justify-content-end) %>

app/views/articles/new.html.erb
<h1 class="text-center">Write a new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

  <% if @article.user %>
    <small>by <%= link_to @article.user.username, user_path(@article.user) %></small>
  <% end%>

<p class="lead"><%= simple_format(@article.description) %></p>

<hr>
<% if logged_in? && (@article.user == current_user || current_user.admin?) %>
  <p>
    <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-xs btn-outline-info" %>
    <%= link_to 'Delete', article_path(@article), class: "btn btn-xs btn-outline-danger", method: :delete, data: { confirm: "Are you sure you want to delete the article?" } %>
  </p>
<% end %>

<p>
  <%= link_to '← Back to article listing', articles_path %>  
</p>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <hr>
    <small>Copyright &copy; 2018, Alpha Blog by <a href="http://idevia.in">iDevia</a></small>
    
    <nav class="float-right">
    <ul class="list-unstyled">
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
  </div>
  
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-sm-12">
      
      <% flash.each do |name, msg| %>
        <div class='alert alert-<%="#{name}" %>'>
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>  
      <% end %>
    
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <%= link_to "Alpha Blog", root_path, class: "navbar-brand logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      
      <li class="nav-item">
        <%= link_to "Articles", articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Users", users_path, class: "nav-link" %>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Actions
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "New article", new_article_path, class: "dropdown-item" %>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Profile
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            
            <%= link_to "Edit profile", edit_user_path(current_user), class: "dropdown-item" %>
            
            <%= link_to "View profile", user_path(current_user), class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "Logout",  logout_path, method: :delete, class: "nav-link" %>
        </li>
        <% if current_user.admin? %>
          <li class="nav-item">
             <button class="btn btn-outline-success disabled my-2 my-sm-0">Admin</button>
          </li>
        <% end %>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Signup", signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <!--<form class="form-inline my-2 my-lg-0">-->
    <!--  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
    <!--  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
    <!--</form>-->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Alpha Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/about.html.erb
<h1>This is about page</h1>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class="jumbotron mt-5 text-center">
  <h1 class="display-4">Alpha Blog</h1>
  <p class="lead">Super simplified blog for all. This is 100% free.</p>
  <p>To get started</p>
  <p class="lead">
    <%= link_to "Signup now", signup_path, class: "btn btn-primary btn-lg" %>
  </p>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any?  %>
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
      <div class="card text-danger border-danger">
        
        <div class="card-body">
          <h5 class="card=title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited the form from being saved:
          </h5>
          <ul>
            <% obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_for @user do |f| %>

  <div class="form-group row mt-4">
    
    <div class="col-sm-2">
      <%= f.label :username, class: "col-form-label" %>
    </div>
    
    <div class="col-sm-8">
      <%= f.text_field :username, class: "form-control", placeholder: "Enter username" %>
    </div>
  </div>
  
  <div class="form-group row">
    
    <div class="col-sm-2">
      <%= f.label :email, class: "col-form-label" %>
    </div>
    
    <div class="col-sm-8">
      <%= f.text_field :email, class: "form-control", placeholder: "Enter email" %>
    </div>
  </div>
  
  <div class="form-group row">
    
    <div class="col-sm-2">
      <%= f.label :password, class: "col-form-label" %>
    </div>
    
    <div class="col-sm-8">
      <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
    </div>
  </div>
  
  <div class="form-group row">
    <div class="col-sm-8 offset-sm-2">
      <%= f.submit(@user.new_record? ? "Sign up" : "Update", class: "btn btn-primary") %>
    </div>
  </div>

<% end %> 

app/views/users/edit.html.erb
<h1>Edit your profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1>All Alpha Bloggers</h1>
<% @users.each do |user| %>
  <div class="media">
    <%= gravatar_for user, size: 50 %>
    <div class="media-body">
      <h5 class="mt-0"><%= link_to user.username, user_path(user) %></h5>
      <%= pluralize(user.articles.count, "article") if user.articles %>
      <% if logged_in? && current_user.admin? %>
        <%= link_to "Delete this user", user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete the user and all their articles?" }, class: "btn btn-xs btn-outline-danger" %>
      <% end %>
    </div>
  </div>
<% end %>

<%= will_paginate @clients, list_classes: %w(pagination justify-content-end) %>

app/views/users/new.html.erb
<h1>Signup for Alpha Blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1>Welcome to <%= @user.username %>'s page</h1>

<div class="row">
  <div class="col-md-4">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>

<h4><%= @user.username %>'s articles</h4>

<%= render 'articles/articles', obj: @user_articles %>

<%= will_paginate @user_articles, list_classes: %w(pagination justify-content-end) %>